name: CI

# 1) Run on every push to main
on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # 2) Grab your code
      - uses: actions/checkout@v4

      # 3) Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 4) Install dependencies
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      # 5) Run a simple syntax check
      - name: Lint with flake8
        run: flake8 .
